### ISSUE TITLE
Think I need a "colmap" module to run your demos.

### ISSUE THREAD

**Issue by Fusroda-h** [kunalchelani/Line2Point#2]
I think I need a "colmap" module to properly run "Recovery.py" and "Utils.py".

I tried to find "read_model" or "load_points_and_setup_from_ply" on _https://colmap.github.io/install.html_

But I couldn't find it, so I assume that their is another customized colmap module which I couldn't find any.

Therefore, I hope you provide "colmap" module which you used. Thank you.

**Comment by StanleyOf427** [comment]
The way I tried is to get python script from colmap 3.5 source code, under folder 'scripts/python', then you will need to create new folder 'colmap' under 'Line2Point' source code folder, finally copy 'read_model.py' to the new location and run 'Recovery.py' with necessary parameters.

**Comment by Fusroda-h** [comment]
Thanks!
It worked.

**Comment by kunalchelani** [comment]
Thanks @StanleyOf427 and @Fusroda-h. I have added the necessary files. Closing this :)
