### ISSUE TITLE
The code ran with an error

### ISSUE THREAD

**Issue by ymx2000** [kunalchelani/Line2Point#5]
When we run the command line python Recover.py --input_type ply --use_fraction_pts 1 --num_refine_iterations 30 --write_colmap True --write_ply True --clean_output True 

When we run it, we get an error:
  Traceback (most recent call last):
    File "Recover.py", line 42, in <module>
      pts, lines = load_points_and_setup_from_ply(args.input_ply_fname, args.use_fraction_pts)
  NameError: name 'load_points_and_setup_from_ply' is not defined
  
  What should I do about it?

**Comment by kunalchelani** [comment]
Hi! Not sure why this would occur as the method is defined in Utils.py, can you try to explicitly import the method load_points_and_setup_from_ply from Utils?

**Comment by ymx2000** [comment]
When I searched Utils.py, there was no result for load_points_and_setup_from_ply; it wasn't there.
Only the filter_and_write_ply, filter_thrice_and_write_ply, and write_ests_to_ply functions are available for ply files
Please check if the Utils.py file uploaded by Github is wrong. Thank you!


-----原始邮件-----
发件人:"Kunal Chelani" ***@***.***>
发送时间:2024-03-05 17:31:11 (星期二)
收件人: kunalchelani/Line2Point ***@***.***>
抄送: ymx2000 ***@***.***>, Author ***@***.***>
主题: Re: [kunalchelani/Line2Point] The code ran with an error (Issue #5)






Hi! Not sure why this would occur as the method is defined in Utils.py, can you try to explicitly import the method load_points_and_setup_from_ply from Utils?

**Comment by kunalchelani** [comment]
You're right. The method for reading points from ply is missing from the Utils.ply file. It is something I missed when I pushed the original code. I will add this, probably by end of this week. If this is something you would prefer to have earlier than that, I recommend it is simple enough to write the required function, reading the ply file using open3d and then randomly sampling the required fraction of points.

**Comment by ymx2000** [comment]
Hello, I'm sorry to bother you again. I have some details about the code that I would like to consult.
After I pass the Colmap data format file, does the code automatically convert 3d points to 3D lines and then back to 3D points?



-----原始邮件-----
发件人:"Kunal Chelani" ***@***.***>
发送时间:2024-03-05 21:05:10 (星期二)
收件人: kunalchelani/Line2Point ***@***.***>
抄送: ymx2000 ***@***.***>, Author ***@***.***>
主题: Re: [kunalchelani/Line2Point] The code ran with an error (Issue #5)






You're right. The method for reading points from ply is missing from the Utils.ply file. It is something I missed when I pushed the original code. I will add this, probably by end of this week. If this is something you would prefer to have earlier than that, I recommend it is simple enough to write the required function, reading the ply file using open3d and then randomly sampling the required fraction of points.

**Comment by kunalchelani** [comment]
Yes, sampling random lines through points is done around lines 166 of Utils.py. The point positions are estimated from the sampled lines via coarse and refine steps then. So, in short yes, the code samples line directions through 3d points and then recovers 3d point positions.

**Comment by kunalchelani** [comment]
Pushed changes with input ply functionality.
Btw as far as your original argumanets in  "python Recover.py --input_type ply --use_fraction_pts 1 --num_refine_iterations 30 --write_colmap True --write_ply True --clean_output True" are concerned, I'd mention a couple of tips:
1. if you're reading a ply input, you can't save a colmap output.
2. 30 refine iterations would take ages. for a pointcloud of size 100k, each refine iteration takes about an hour (this is definitely not the most efficient implmentation of the recovery algorithm). In general the gain in accuracy is not worth the time after 2-3 refine iterations.

Closing the issue as the original issue is fixed.
